// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import slack "github.com/nlopes/slack"

// SlackRTMInterface is an autogenerated mock type for the SlackRTMInterface type
type SlackRTMInterface struct {
	mock.Mock
}

// GetIncomingEvents provides a mock function with given fields:
func (_m *SlackRTMInterface) GetIncomingEvents() chan slack.RTMEvent {
	ret := _m.Called()

	var r0 chan slack.RTMEvent
	if rf, ok := ret.Get(0).(func() chan slack.RTMEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan slack.RTMEvent)
		}
	}

	return r0
}

// GetInfo provides a mock function with given fields:
func (_m *SlackRTMInterface) GetInfo() *slack.Info {
	ret := _m.Called()

	var r0 *slack.Info
	if rf, ok := ret.Get(0).(func() *slack.Info); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slack.Info)
		}
	}

	return r0
}

// NewOutgoingMessage provides a mock function with given fields: text, channelID, options
func (_m *SlackRTMInterface) NewOutgoingMessage(text string, channelID string, options ...slack.RTMsgOption) *slack.OutgoingMessage {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, text, channelID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *slack.OutgoingMessage
	if rf, ok := ret.Get(0).(func(string, string, ...slack.RTMsgOption) *slack.OutgoingMessage); ok {
		r0 = rf(text, channelID, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slack.OutgoingMessage)
		}
	}

	return r0
}

// SendMessage provides a mock function with given fields: msg
func (_m *SlackRTMInterface) SendMessage(msg *slack.OutgoingMessage) {
	_m.Called(msg)
}
